apiVersion: v1
kind: Pod
metadata:
  name: kubia
spec:
  containers:
  - image: piotrbejenka/kubia
    name: kubia
    ports:
    - name: http
      containerPort: 8080
    - name: https
      containerPort: 8443
